using System.IO;

namespace TechnovertBank.Models
{
    public static class Constant
    {
        public static string projectDirectory = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.FullName;
        public static string filePath = $"{projectDirectory}\\BankingApplication.Database\\Data.json";
        public const string employeeMenu = "Choice\n1.Create Account\n2.AddBank\n3.UpdateAccount\n4.Delete an Account\n5.AddNewEmployee\n6.AddNewCurrency\n7.ModifyServiceCharge\n8.ViewTransactionsForAccount\n9.View Transactions\n10.RevertTransaction\nAny other key to logout.";
        public const string welcomeMessage = "\n\n==============================Welcome to Technovert Banking Solutions=============================.\n********************\n1.Account Holder Login\n2.Bank Employee Login.\n\nPlease enter one option\n********************";
        public const string accountNotFoundError = "Account Does not exists.\n";
        public const string customerPropertiesMenu = "Please enter an option:\n1.Name\n2.Age\n3.Gender\n4.Dob\n5.Aadhar\n6.PAN\n7.Contact Number\n8.Address\nAny other key to exit.";
        public const string accountHolderOptions = "\nChoose any one option:\n1.Deposit\n2.Withdraw\n3.Transfer Amount\n4.Print Transaction history\n5.Check Balance\n6.Logout";
        public const string invalidCredentialsError = "Invalid Credentials. Please try again or enter 0 for Main menu\n";
        public const string genderOptions = "GenderOptions:\n1.Male\n2.Female\n3.Prefer Not to say";
        public const string accountTypeOptions = "Account Type(1.Savings/2.Current)";
        public const string bankAlreadyExists = "A Bank with same name already exists!";
        public const string updateConfirmation = "Are you sure you want the changes to save?(Y/N)";
        public const string deleteAccountConfirmation = "\nAre you sure you want to delete this account?(Y/N)";
        public const string employeeMenuHeader = "\n========================BANK STAFF MENU==========================\n";
        public const string addNewEmployeeHeader = "\n-----------Add New Employee-----------\n";
        public const string designationOptions = "Employee Designation\n1.Manager\n2.Accounts Manager\n3.Financial Analyst\n4.LoanOfficer";
        public const string updateSuccess = "Updated successfully";
        public const string updateFail = "Changes aren't applied!";
        public const string accountDeleteSuccess = "Account Deleted";
        public const string accountDeleteFail = "Account was not deleted. Try again later.";
        public const string bankNotCreated = "Bank not created! Try again.";
        public const string currencyAlreadyExists = "Currency Already Exists!";
        public const string invalidExchangeRate = "Invalid exchange rate";
        public const string revertConfirmation = "Are you sure you want to revert the transaction(Y/N)?\n";
        public const string revertSuccess = "Reverted Successfully!\n";
        public const string revertFail = "Could not revert!";
        public const string otherBankInvolvedRevertFail = "Cannot revert transaction involving other bank.";
        public const string transferModeOptions = "Choose Transfer mode:\n1.RTGS\n2.IMPS";
        public const string selfOrOtherOptions = "Charge type:\n1.Money Transfer Within bank.\n2.Money transfer to other banks";
        public const string noSuchTransaction = "No such transaction found!\n";
        public const string invalidDateFormat = "Invalid Date. Please enter date in valid format YYYYMMDD";
        public const string invalidNameFormat = "Name should not contain digits and should be of length greater than 3.Please enter the valid name. Example: Sam Daniels:\n";
        public const string invalidAgeFormat = "Please enter valid age. Re-enter age:";
        public const string accountCreationHeader = "\t-------Account Creation-------\n";
        public const string employeeInterfaceHeader = "\n===================BANK EMPLOYEE LOGIN===================\n";
        public const string customerInterfaceHeader = "=================CUSTOMER LOGIN================";
        public const string moneyDepositHeader = "\t-------Money Deposit-------\n";
        public const string creditSuccess = "Credited successfully\n";
        public const string unsupportedCurrency = "Unsupported currency type";
        public const string invalidAmount = "Please enter valid amount.\n";
        public const string withdrawlHeader = "\n-------Amount Withdrawl-------\n";
        public const string debitSuccess = "Debited successfully";
        public const string insufficientFunds = "Insufficient funds.\n";
        public const string transferHeader = "-------Amount Transfer-------\n";
        public const string transferSuccess = "Transferred successfully";
        public const string recipientAccountNotFound = "Recipient account doesn't exists.\n";
        public const string transactionHistoryHeader = "\n-------Transaction History-------\n";
        public const string dateOfBirth = "Date of Birth";
        public const string contactNumber = "Contact Number";
        public const string aadharNumber = "Aadhar Number";
        public const string panNumber = "PAN Number";
        public const string address = "Address";
        public const string bankName = "Name of the bank";
        public const string branch = "bank branch";
        public const string accountId = "Account Id";
        public const string updateMenuHeader = "\n--------------UPDATE MENU----------------";
        public const string newCurrencyName = "new currency name";
        public const string currencyName = "Currency Name";
        public const string newExchangeRate = "exchange rate";
        public const string currencyAdded = "Currency has been added successfully!!";
        public const string newChargeValue = "New Charge Value:";
        public const string transactionId = "Transaction Id";
        public const string amountToDeposit = "amount to deposit";
        public const string amountToWithdraw = "amount to withdraw";
        public const string receiverAccountNumber = "Receiver Account Number";
        public const string amountToTransfer = "Amount to Transfer";
        public const string Ifsc = "IFSC";
        public const string viewTransactionsHeader = "\n-----------View Transactions----------\n";
        public const string viewTransactionsOptions = "\n1.On Particular date\n2.All transactions\nPlease enter your choice";
        public const string addBankHeader = "\n-------------ADD BANK---------------\n";
        public const string showTransactionsHeader = "Sno  | Transaction Id\t\t\t\t|     Type     | Amount | Balance | Transaction On\n-----------------------------------------------------------------------------------------------";
        public const string noTransactions = "\nNo transactions to show!\n";
        public const string customerMenuHeader = "\n================CUSTOMER MENU===================";
        public const string invalidUserName = "Invalid Username!\n";
        public const string invalidPassword = "Invalid Password!\n";
        public const string displayTransactionHeader = "Sno  | Transaction Id\t\t\t\t\t   |  Type  \t  | Amount | Balance | Transaction On";
        public const string lineBreak = "-----------------------------------------------------------------------------------------------------------------";
        public const string loginSuccess = "\n*********************Logged In**********************\n";
    }
}